GHA

diff --git a/.github/workflows/drift.yaml b/.github/workflows/drift.yaml
--- a/.github/workflows/drift.yaml
+++ b/.github/workflows/drift.yaml
@@ -39,9 +39,90 @@ on:
   push:
     branches: [ "main" ]
 
+  name: Terraform Drift Detection
+
+on:
+  workflow_dispatch:
+
+  schedule:
+    - cron: "0 2 * * *"
+
+permissions:
+  id-token: write
+  contents: read
+
 jobs:
-  debug:
+  drift:
     runs-on: ubuntu-latest
 
+    env:
+      AWS_REGION: us-east-1
+
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::224761220970:role/GitHubActionsOIDCRole
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Verify AWS Identity
+        run: aws sts get-caller-identity
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.15.8
+
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Validate
+        run: terraform validate
+
+      - name: Terraform Format Check
+        run: terraform fmt -check
+
+      - name: Terraform Plan (Detect Drift)
+        id: plan
+        shell: bash
+        run: |
+          set +e
+
+          terraform plan \
+            -detailed-exitcode \
+            -out=tfplan
+
+          EXIT_CODE=$?
+
+          echo "exitcode=$EXIT_CODE" >> "$GITHUB_OUTPUT"
+
+          if [ "$EXIT_CODE" -eq 1 ]; then
+            echo "Terraform plan failed."
+            exit 1
+          fi
+
+          exit 0
+
+      - name: No Drift
+        if: steps.plan.outputs.exitcode == '0'
+        run: |
+          echo "No infrastructure drift detected."
+
+      - name: Drift Detected
+        if: steps.plan.outputs.exitcode == '2'
+        run: |
+          echo "Terraform detected infrastructure drift."
+
+      - name: Show Plan
+        if: steps.plan.outputs.exitcode == '2'
+        run: terraform show -no-color tfplan
+
+# jobs:
+#   debug:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - uses: actions/checkout@v4
