Add Terraform drift detection

diff --git a/.github/workflows/drift.yaml b/.github/workflows/drift.yaml
--- a/.github/workflows/drift.yaml
+++ b/.github/workflows/drift.yaml
@@ -33,103 +33,158 @@
 
 #           echo "Token received: ${#TOKEN} characters"
 
+# name: Terraform Drift Detection
+
+# on:
+#   push:
+#     branches: [ "main" ]
+#   schedule:
+#     - cron: "0 2 * * *"  # daily at 2 AM UTC
+#   workflow_dispatch: {}
+
+# permissions:
+#   id-token: write
+#   contents: read
+
+# jobs:
+#   drift:
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         working-directory: ./terraform   # <-- adjust to your actual path #######
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+
+#       - name: Configure AWS Credentials
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           role-to-assume: arn:aws:iam::224761220970:role/github-actions-oidc-role
+#           aws-region: us-east-1
+
+#       - name: Verify AWS Identity
+#         run: aws sts get-caller-identity
+
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v3
+#         with:
+#           terraform_version: 1.15.8
+
+#       - name: Terraform Init
+#         run: terraform init -input=false
+
+#       - name: Terraform Validate
+#         run: terraform validate
+
+#       - name: Terraform Plan (Detect Drift)
+#         id: plan
+#         run: |
+#           set +e
+#           terraform plan -detailed-exitcode -out=tfplan -input=false
+#           echo "exitcode=$?" >> "$GITHUB_OUTPUT"
+#           set -e
+
+#       - name: No Drift Detected
+#         if: steps.plan.outputs.exitcode == '0'
+#         run: echo "✅ No infrastructure drift detected."
+
+#       - name: Drift Detected
+#         if: steps.plan.outputs.exitcode == '2'
+#         run: |
+#           echo "⚠️ Infrastructure drift detected."
+#           terraform show -no-color tfplan
+#           exit 1
+
+#       - name: Plan Failed
+#         if: steps.plan.outputs.exitcode == '1'
+#         run: |
+#           echo "❌ Terraform plan failed to execute."
+#           exit 1
+#     ##step that auto-generates the terraform import commands for whatever shows up as unmanaged
+#       - name: Install boto3
+#         run: pip install boto3
+
+#       - name: Export Terraform State as JSON
+#         run: terraform show -json > tfstate.json
+
+#       - name: Check for Unmanaged AWS Resources
+#         id: unmanaged_check
+#         continue-on-error: true
+#         run: python3 compare_drift.py --tf-state tfstate.json --region us-east-1 --out unmanaged.json
+
+#       - name: Generate Import Commands for Unmanaged Resources
+#         if: steps.unmanaged_check.outcome == 'failure'
+#         run: python3 generate_import_commands.py --report unmanaged.json
+
+#       - name: Upload Unmanaged Resources Report
+#         if: steps.unmanaged_check.outcome == 'failure'
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: unmanaged-resources-${{ github.run_id }}
+#           path: |
+#             tfstate.json
+#             unmanaged.json
+#             imported_resources.tf
+#             import_commands.sh
+#           retention-days: 14
+
+#       - name: Fail Job if Unmanaged Resources Found
+#         if: steps.unmanaged_check.outcome == 'failure'
+#         run: |
+#           echo "❌ Unmanaged AWS resources detected — see uploaded artifact for import commands."
+#           exit 1
+
+
 name: Terraform Drift Detection
 
 on:
-  push:
-    branches: [ "main" ]
   schedule:
-    - cron: "0 2 * * *"  # daily at 2 AM UTC
-  workflow_dispatch: {}
-
-permissions:
-  id-token: write
-  contents: read
+    - cron: "0 */6 * * *"   # Run every 6 hours
+  workflow_dispatch:
 
 jobs:
-  drift:
+  drift-detection:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./terraform   # <-- adjust to your actual path #######
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::224761220970:role/github-actions-oidc-role
-          aws-region: us-east-1
-
-      - name: Verify AWS Identity
-        run: aws sts get-caller-identity
-
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.15.8
 
       - name: Terraform Init
-        run: terraform init -input=false
+        run: terraform init
 
-      - name: Terraform Validate
-        run: terraform validate
-
-      - name: Terraform Plan (Detect Drift)
+      - name: Terraform Plan
         id: plan
+        continue-on-error: true
+        run: terraform plan -detailed-exitcode -out=tfplan
+
+      - name: Send drift email
+        if: steps.plan.outputs.exitcode == '2'
+        env:
+          AWS_REGION: us-east-1
+          SES_FROM: ${{ abbysac@gmail.com }}
+          SES_TO: ${{ camleous@yahoo.com }}
         run: |
-          set +e
-          terraform plan -detailed-exitcode -out=tfplan -input=false
-          echo "exitcode=$?" >> "$GITHUB_OUTPUT"
-          set -e
+          aws ses send-email \
+            --region "us-east-1" \
+            --from "$SES_FROM" \
+            --destination "ToAddresses=$SES_TO" \
+            --message '{
+              "Subject": {
+                "Data": "Terraform Drift Detected"
+              },
+              "Body": {
+                "Text": {
+                  "Data": "Terraform has detected drift in your AWS infrastructure.\n\nReview the Terraform plan and determine whether the changes were intentional."
+                }
+              }
+            }'
 
-      - name: No Drift Detected
-        if: steps.plan.outputs.exitcode == '0'
-        run: echo "✅ No infrastructure drift detected."
-
-      - name: Drift Detected
+      - name: Fail if drift detected
         if: steps.plan.outputs.exitcode == '2'
         run: |
-          echo "⚠️ Infrastructure drift detected."
-          terraform show -no-color tfplan
-          exit 1
-
-      - name: Plan Failed
-        if: steps.plan.outputs.exitcode == '1'
-        run: |
-          echo "❌ Terraform plan failed to execute."
-          exit 1
-    ##step that auto-generates the terraform import commands for whatever shows up as unmanaged
-      - name: Install boto3
-        run: pip install boto3
-
-      - name: Export Terraform State as JSON
-        run: terraform show -json > tfstate.json
-
-      - name: Check for Unmanaged AWS Resources
-        id: unmanaged_check
-        continue-on-error: true
-        run: python3 compare_drift.py --tf-state tfstate.json --region us-east-1 --out unmanaged.json
-
-      - name: Generate Import Commands for Unmanaged Resources
-        if: steps.unmanaged_check.outcome == 'failure'
-        run: python3 generate_import_commands.py --report unmanaged.json
-
-      - name: Upload Unmanaged Resources Report
-        if: steps.unmanaged_check.outcome == 'failure'
-        uses: actions/upload-artifact@v4
-        with:
-          name: unmanaged-resources-${{ github.run_id }}
-          path: |
-            tfstate.json
-            unmanaged.json
-            imported_resources.tf
-            import_commands.sh
-          retention-days: 14
-
-      - name: Fail Job if Unmanaged Resources Found
-        if: steps.unmanaged_check.outcome == 'failure'
-        run: |
-          echo "❌ Unmanaged AWS resources detected — see uploaded artifact for import commands."
-          exit 1
+          echo "Terraform drift detected!"
+          exit 2
